### ISSUE TITLE
VOXEDIT: Keep listening key inputs when in other overlays

### ISSUE THREAD

**Issue by DryByte** [mgerhardy/vengi#282]
When you set the point of view to eye, and you start typing in other part of the UI, like for renaming a layer or the file name, camera will start moving when you press WASD.

**Comment by mgerhardy** [comment]
Thanks for the report - should be fixed in latest master. But it's needed to cycle through a binding schema in the ui to reset the current bindings

![Bildschirmfoto vom 2023-04-23 19-15-41](https://user-images.githubusercontent.com/577713/233854511-82631a19-4d89-4326-aced-b529a535afa4.png)

just to a different one, and then back to the one you want.
